worker_processes  1;
events {
    worker_connections  1024;
}
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       9000;
        server_name  localhost;

        location / {
            root   /code/dist;
            index  index.html index.htm;
            # 这一句是前端路由刷新不报 404 的关键
            try_files $uri $uri/ /index.html;
        }
    }
}
